version: '2.4'
services:
  servidorcasero:
    build: .
    ports:
      - 5003:5000
        #read_only: true
    cap_drop:
      - all
    cap_add:
      - chown
      - setuid
      - setgid
      - sys_admin
      - mknod
    security_opt:
      - apparmor=unconfined
      - seccomp=unconfined
